# Generated by Django 3.2.4 on 2021-06-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210607_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
