# Generated by Django 3.2.4 on 2021-06-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='friends',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
