# Generated by Django 3.2.4 on 2021-06-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210607_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('talent', models.JSONField(blank=True, default=list, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('content', models.CharField(max_length=500)),
                ('pictures', models.FileField(blank=True, null=True, upload_to='images/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.masteruser')),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.CreateModel(
            name='PersonUser',
            fields=[
                ('masteruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.masteruser')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
            bases=('api.masteruser',),
        ),
        migrations.CreateModel(
            name='TalentUser',
            fields=[
                ('masteruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.masteruser')),
                ('name', models.CharField(max_length=30)),
                ('members', models.JSONField(blank=True, default=list, editable=False)),
                ('apple_music_id', models.CharField(blank=True, max_length=100)),
                ('spotify_id', models.CharField(blank=True, max_length=100)),
                ('genres', models.JSONField(blank=True, default=list, editable=False)),
            ],
            bases=('api.masteruser',),
        ),
        migrations.CreateModel(
            name='VenueUser',
            fields=[
                ('masteruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.masteruser')),
                ('name', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=100)),
            ],
            bases=('api.masteruser',),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='posts',
            field=models.ManyToManyField(to='api.Post'),
        ),
        migrations.AddField(
            model_name='masteruser',
            name='user_network',
            field=models.ManyToManyField(to='api.MasterUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='api.PersonUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venueuser'),
        ),
    ]
