# Generated by Django 3.2.4 on 2021-06-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210607_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pictures',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='posts',
            field=models.ManyToManyField(editable=False, to='api.Post'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='user_network',
            field=models.ManyToManyField(editable=False, to='api.MasterUser'),
        ),
    ]
