# Generated by Django 3.2.4 on 2021-06-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210607_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteruser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='venueuser',
            name='lat',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='venueuser',
            name='long',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
